### Example config file for snb-generate_all

# General/distortion options
oxidation_states:
  Cd: 2
  Te: -2
distortion_increment: 0.1
bond_distortions: [-0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
distorted_elements:  # (Default = None, distorts nearest neighbours)
  Int_Cd_2:
    Cd
dict_number_electrons_user:  # (Default = None, determines from electron change at defect site)
  Int_Cd_2:
    2

# Rattle options
stdev: 0.25
d_min: 2.25  # (Default = 80% of auto-determined bulk bond length)
n_iter: 1
active_atoms: None  # (Default = all atoms)
nbr_cutoff: 5
width: 0.1
max_attempts: 5000
max_disp: 2.0
seed: 42
local_rattle: True

# Defects section: to specify charge states and defect index/frac coords
defects:
  vac_1_Cd:  # Name should match your defect structure file/folder
    charges: [0, -1, -2]  # List of charge states
    defect_coords: [0.0, 0.0, 0.0]  # Fractional coords for vacancies!
  Int_Cd_2:
    charges: [0, +1, +2]
    defect_index: -1