build:
  os: "ubuntu-latest"
  tools:
    python: ['3.8', '3.9']

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
