name: pip install ShakeNBreak

on:
  workflow_run:
    workflows: ["Release and publish"]
    branches: [main]
    types:
      - completed  # only test when new release has been deployed to PyPI
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    # only run when tests have passed (or manually triggered)

    strategy:
      fail-fast: false

      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        os: [ ubuntu-latest,macos-latest,windows-latest ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sleep 10m  # wait 10 minutes for PyPI to update with the new release
          python -m pip install --upgrade pip
          pip install shakenbreak[tests]  # install only from PyPI

      - name: Test
        run:  |
          pytest --mpl -vv tests  # test everything
          
      - name: Generate GH Actions test plots
        if: always()  # always generate the plots, even if the tests fail
        run:  |
          # Generate the test plots in case there were any failures:
          pytest --mpl-generate-path=tests/remote_baseline tests/test_plotting.py
          pytest --mpl-generate-path=tests/remote_baseline tests/test_shakenbreak.py

      # Upload test plots
      - name: Archive test plots
        if: always()  # always upload the plots, even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: output-plots
          path: tests/remote_baseline
